import turtle
import random
### zmaksymalizowanie okna wyswietlania
screen = turtle.Screen()
screen.setup(width = 1.0, height = 1.0)

def obrazek():
    t=turtle.Turtle()
    turtle.title("Obraz 2D EK")
    t.shape("turtle")
    t.speed(100)
    turtle.screensize(750,750)
    turtle.colormode(255)
    turtle.bgcolor(59, 109, 217)
    t.color("white")
    t.penup()
    t.setx(-780)
    t.sety(-300)
    t.pendown()
    t.begin_fill()
    t.forward(1600)
    t.right(90)
    t.forward(300)
    t.right(90)
    t.forward(1600)
    t.right(90)
    t.forward(300)
    t.end_fill()
    ### rysowanie plotu
    def plotek():
        t1=turtle.Turtle()
        t1.shape("turtle")
        t1.speed(100)
        t1.pensize(5)
        t1.color("white")
        t1.penup()
        t1.goto(-760, -300)
        t1.pendown()
        def plotek1():
            t1.begin_fill()
            t1.left(90)
            t1.forward(70)
            t1.right(45)
            t1.forward(10)
            t1.right(90)
            t1.forward(10)
            t1.right(45)
            t1.forward(70)
            t1.left(90)
            t1.forward(10)
            t1.end_fill()
        i=0
        while i <63 :
            plotek1()
            i+=1
            ### rysowanie domku
    def domek():
        t2=turtle.Turtle()
        t2.pensize(10)
        t2.shape("turtle")
        t2.speed(100)
        t2.penup()
        t2.sety(-296)
        t2.setx(-200)
        t2.pendown()
        turtle.colormode(255)
        t2.color(186, 134, 56)
        t2.begin_fill()
        t2.left(90)
        t2.forward(300)
        t2.right(90)
        t2.forward(300)
        t2.right(90)
        t2.forward(300)
        t2.right(90)
        t2.forward(300)
        t2.end_fill()

        t2.setx(-100)
        t2.color(173, 44, 35)
        ### rysowanie drzwi
        def drzwi():
            t2.begin_fill()
            t2.right(90)
            t2.forward(100)
            t2.right(90)
            t2.forward(50)
            t2.right(90)
            t2.forward(100)
            t2.right(90)
            t2.forward(50)
            t2.end_fill()

            t2.pensize(5)
            t2.right(90)
            t2.forward(50)
            t2.right(90)
            t2.color(186, 134, 56)
            t2.forward(2)
            t2.color("black")
            t2.circle(1)
        drzwi()
        ### rysowanie okien
        def okna():
            t2.penup()
            t2.goto(-170,-100)
            t2.pendown()
            t2.begin_fill()
            t2.color(51, 182, 222)
            t2.forward(50)
            t2.left(90)
            t2.forward(50)
            t2.left(90)
            t2.forward(50)
            t2.left(90)
            t2.forward(50)
            t2.end_fill()
            t2.color(166, 95, 41)

            t2.left(90)
            t2.forward(50)
            t2.left(90)
            t2.forward(50)
            t2.left(90)
            t2.forward(50)
            t2.left(90)
            t2.forward(50)
            t2.left(90)
            t2.forward(25)
            t2.left(90)
            t2.forward(50)
            t2.right(90)

            t2.penup()
            t2.goto(-10,-100)
            t2.pendown()

            t2.begin_fill()
            t2.color(51, 182, 222)
            t2.forward(50)
            t2.left(90)
            t2.forward(50)
            t2.left(90)
            t2.forward(50)
            t2.left(90)
            t2.forward(50)
            t2.end_fill()
            t2.color(166, 95, 41)

            t2.left(90)
            t2.forward(50)
            t2.left(90)
            t2.forward(50)
            t2.left(90)
            t2.forward(50)
            t2.left(90)
            t2.forward(50)
            t2.left(90)
            t2.forward(25)
            t2.left(90)
            t2.forward(50)
            t2.right(90)

        okna()
        ### rysowanie dachu
        def dach():
            t2.penup()
            t2.goto(-220,-10)
            t2.pendown()
            t2.pensize(10)
            t2.color("white")
            t2.begin_fill()
            t2.left(70)
            t2.forward(120)
            t2.right(70)
            t2.forward(330)
            t2.right(110)
            t2.forward(120)
            t2.right(70)
            t2.forward(330)
            t2.end_fill()
        dach()
        ### rysowanie kominu
        def komin():
            t2.penup()
            t2.color(74, 69, 69)
            t2.goto(60,105)
            t2.pendown()
            t2.pensize(7)
            t2.begin_fill()
            t2.right(90)
            t2.forward(30)
            t2.left(90)
            t2.forward(10)
            t2.right(90)
            t2.forward(20)
            t2.right(90)
            t2.forward(40)
            t2.right(90)
            t2.forward(20)
            t2.right(90)
            t2.forward(10)
            t2.left(90)
            t2.forward(30)
            t2.right(90)
            t2.forward(20)
            t2.end_fill()
        komin()
        ### rysowanie dymu
        def dymek():
            t2.penup()
            t2.color("white")
            t2.goto(60,170)
            t2.pendown()
            t2.pensize(4)
            t2.right(90)
            for j in range(45):
                t2.right(1)
                t2.forward(1)
            for j in range(45):
                t2.left(1)
                t2.forward(1)
            t2.penup()
            t2.goto(70,170)
            t2.pendown()
            for j in range(45):
                t2.right(1)
                t2.forward(1)
            for j in range(45):
                t2.left(1)
                t2.forward(1)
            t2.penup()
            t2.goto(80, 170)
            t2.pendown()
            for j in range(45):
                t2.right(1)
                t2.forward(1)
            for j in range(45):
                t2.left(1)
                t2.forward(1)
                t2.hideturtle()
        dymek()
        ### rysowanie slonca
    def slonce():
        t3=turtle.Turtle()
        t3.shape("turtle")
        t3.pensize(5)
        turtle.colormode(255)
        t3.color(220, 240, 41)
        t3.speed(100)
        t3.penup()
        t3.goto(-820,350)
        t3.pendown()
        t3.begin_fill()
        k=0
        while k<50:
            t3.forward(300)
            t3.left(170)
            if abs(t3.pos()) < 1:
                break
            k+=1
        t3.end_fill()
            ### rysowanie sniegu + losowe rozmieszczenie
    def snieg():
        t4 = turtle.Turtle()
        t4.shape("turtle")
        t4.speed(0)
        t4.color("white")

        def platek_sniegu(rozmiar):
            t4.penup()
            t4.forward(10 * rozmiar)
            t4.left(45)
            t4.pendown()

            for i in range(8):
                galaz(rozmiar)
                t4.left(45)

        def galaz(rozmiar):
            for i in range(3):
                for i in range(3):
                    t4.forward(10.0 * rozmiar / 3)
                    t4.back(10.0 * rozmiar / 3)
                    t4.right(45)
                t4.left(90)
                t4.back(10.0 * rozmiar / 3)
                t4.left(45)
            t4.right(90)
            t4.forward(10.0 * rozmiar)

        for i in range(20):
            x = random.randint(-700, 700)
            y = random.randint(-300, 300)
            rozm_platka = 1
            t4.penup()
            t4.goto(x, y)
            t4.pendown()
            platek_sniegu(rozm_platka)
        t4.hideturtle()

    t5 = turtle.Turtle()
    ### rysowanie chmur
    def chmury():
        t.shape("turtle")
        t5.penup()
        t5.goto(-300,300)
        t5.pendown()
        t5.color("white")
        l = 0
        while l < 3:
            t5.begin_fill()
            t5.speed(100)
            t5.forward(150)
            t5.left(90)
            t5.forward(20)
            for x in range(1, 15):
                t5.left(10)
                t5.forward(10)

            t5.left(220)
            for y in range(1, 18):
                t5.left(10)
                t5.forward(12)

            t5.left(200)
            for z in range(1, 18):
                t5.left(10)
                t5.forward(15)

            t5.forward(18)
            t5.left(90)
            t5.forward(260)
            t5.end_fill()
            t5.penup()
            t5.forward(450)
            t5.pendown()
            t5.hideturtle()
            l += 1

    t6 = turtle.Turtle()
    t6.shape("turtle")
    t6.speed(100)
    t6.penup()
    t6.goto(-700,-170)
    t6.pendown()
    ### rysowanie choinki
    def choinka1():
        def trojkat():
            t6.color("green")
            t6.begin_fill()
            t6.left(45)
            t6.forward(100)
            t6.right(90)
            t6.forward(100)
            t6.right(135)
            t6.forward(142)
            t6.end_fill()
            t6.right(180)

        trojkat()
        t6.penup()
        t6.sety(-220)
        t6.pendown()
        trojkat()
        t6.penup()
        t6.sety(-270)
        t6.pendown()
        trojkat()
        t6.forward(60)
        t6.color("brown")
        t6.begin_fill()
        t6.right(90)
        t6.forward(30)
        t6.left(90)
        t6.forward(30)
        t6.left(90)
        t6.forward(30)
        t6.end_fill()
        t6.right(90)
        t6.hideturtle()

        ### wywołanie wszystkich funkcji + pozycja 2 choinki
    slonce()
    chmury()
    snieg()
    plotek()
    choinka1()
    t6.penup()
    t6.goto(600,-170)
    t6.pendown()
    choinka1()
    domek()
obrazek()
turtle.exitonclick()
